# Generated by Django 5.1.4 on 2024-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_formuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='formuser',
            name='courses',
            field=models.ManyToManyField(related_name='form_users', to='myapp.course'),
        ),
    ]
