# Generated by Django 5.1.4 on 2024-12-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
