# Generated by Django 5.1.4 on 2024-12-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_pdf_uploaded_at_alter_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formuser',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuser',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='form_users', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='formuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='formuser',
            name='user_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
